### ISSUE TITLE
Invalid button data

### ISSUE THREAD

**Issue by tmteam** [NatShep/ChoTISkazal#42]
```
WYS Control Panel, [19.12.20 02:05]
❗️  msg { ChatInfo: 91686883, msg: " exception: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63" }

WYS Control Panel, [19.12.20 02:05]
❗️  msg { ChatInfo: 91686883, msg: "Fatal on run: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78" }

WYS Control Panel, [19.12.20 02:05]
❗️  msg { ChatInfo: 91686883, msg: "Faulted System.AggregateException: One or more errors occurred. (Bad Request: BUTTON_DATA_INVALID)
 ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78
   --- End of inner exception stack trace ---" }

WYS Control Panel, [19.12.20 02:06]
❗️  msg { ChatInfo: 91686883, msg: " exception: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63" }

WYS Control Panel, [19.12.20 02:06]
❗️  msg { ChatInfo: 91686883, msg: "Fatal on run: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78" }

WYS Control Panel, [19.12.20 02:06]
❗️  msg { ChatInfo: 91686883, msg: "Faulted System.AggregateException: One or more errors occurred. (Bad Request: BUTTON_DATA_INVALID)
 ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78
   --- End of inner exception stack trace ---" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: " exception: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: "Fatal on run: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: "Faulted System.AggregateException: One or more errors occurred. (Bad Request: BUTTON_DATA_INVALID)
 ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 100
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78
   --- End of inner exception stack trace ---" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: " exception: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.ShowMainMenu() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 164
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 94
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: "Fatal on run: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.ShowMainMenu() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 164
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 94
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78" }

WYS Control Panel, [19.12.20 02:12]
❗️  msg { ChatInfo: 91686883, msg: "Faulted System.AggregateException: One or more errors occurred. (Bad Request: BUTTON_DATA_INVALID)
 ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 66
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.EnterSingleWordAsync(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 70
   at Chotiskazal.Bot.ChatFlows.AddingWordsMode.Enter(UserModel user, String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\AddingWordsFlow.cs:line 34
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.ShowMainMenu() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 164
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.HandleMainScenario(String mainMenuCommandOrNull) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 94
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 63
   at Chotiskazal.Bot.ChatFlows.ChatRoomFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\ChatRoomFlow.cs:line 78
   --- End of inner exception stack trace ---" }
```

**Comment by tmteam** [comment]
translate word 'transparency'

**Comment by tmteam** [comment]
to long translation. 

Check added: OriginWord.Length + translation.Length <=32
