### ISSUE TITLE
Translation fails on word 'Coefficient'

### ISSUE THREAD

**Issue by tmteam** [NatShep/ChoTiSkazal#59]
Just try to translate 'Coefficient' and get following error:

```

WYS Control Panel, [20 Nov 2021, 03:24:17]:
...  msg { ChatInfo: 62634148, msg: " exception: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[][] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 72
   at Chotiskazal.Bot.ChatFlows.LastTranslationHandler.SendTranslationMessage(String markdownMessage, String transcription, Boolean[] selectionMarks) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\LastTranslationHandler.cs:line 101
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.EnterSingleWordAsync(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 87
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.Enter(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 31
   at Chotiskazal.Bot.ChatFlows.MainFlow.HandleMainScenario(Nullable`1 command) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 130
   at Chotiskazal.Bot.ChatFlows.MainFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 55" }

❗  msg { ChatInfo: 62634148, msg: "Fatal on run: Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[][] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 72
   at Chotiskazal.Bot.ChatFlows.LastTranslationHandler.SendTranslationMessage(String markdownMessage, String transcription, Boolean[] selectionMarks) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\LastTranslationHandler.cs:line 101
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.EnterSingleWordAsync(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 87
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.Enter(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 31
   at Chotiskazal.Bot.ChatFlows.MainFlow.HandleMainScenario(Nullable`1 command) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 130
   at Chotiskazal.Bot.ChatFlows.MainFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 55
   at Chotiskazal.Bot.ChatFlows.MainFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 71" }

❗  msg { ChatInfo: 62634148, msg: "Faulted System.AggregateException: One or more errors occurred. (Bad Request: BUTTON_DATA_INVALID)
 ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: BUTTON_DATA_INVALID
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Chotiskazal.Bot.ChatIO.SendMarkdownMessageAsync(String message, InlineKeyboardButton[][] buttons) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatIO.cs:line 72
   at Chotiskazal.Bot.ChatFlows.LastTranslationHandler.SendTranslationMessage(String markdownMessage, String transcription, Boolean[] selectionMarks) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\LastTranslationHandler.cs:line 101
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.EnterSingleWordAsync(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 87
   at Chotiskazal.Bot.ChatFlows.TranslateWordsFlow.Enter(String word) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\TranslateWordsFlow.cs:line 31
   at Chotiskazal.Bot.ChatFlows.MainFlow.HandleMainScenario(Nullable`1 command) in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 130
   at Chotiskazal.Bot.ChatFlows.MainFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 55
   at Chotiskazal.Bot.ChatFlows.MainFlow.Run() in C:\Apps\Chotiskazal\Chotiskazal\Chtotiskazal\Chotiskazal.Bot\ChatFlows\MainFlow.cs:line 71
   --- End of inner exception stack trace ---" }
```

**Comment by tmteam** [comment]
May be callback is too long?
